In [22]:
import numpy as np
import pandas as pd
diabetes = pd.read_csv('/content/diabetes.csv')
diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

Always pirnt head, tail, columns, shape, and total
number of missing values

In [23]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [24]:
diabetes.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [25]:
diabetes.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [26]:
diabetes.shape

(768, 9)

In [27]:
diabetes.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [28]:
diabetes.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

set input to x and output to y, and set it as an array (for tha add '.values')
output alwyas should be 1 dimensional

In [29]:
x = diabetes.iloc[:,:-1].values
y = diabetes.iloc[:,-1].values
x.ndim

2

set training and testing data

In [30]:
from sklearn.model_selection import train_test_split
# 70%(,70) for training and and 30% for testing
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.30)

In [31]:
x_train

array([[2.00e+00, 1.46e+02, 0.00e+00, ..., 2.75e+01, 2.40e-01, 2.80e+01],
       [2.00e+00, 8.10e+01, 7.20e+01, ..., 3.01e+01, 5.47e-01, 2.50e+01],
       [4.00e+00, 1.22e+02, 6.80e+01, ..., 3.50e+01, 3.94e-01, 2.90e+01],
       ...,
       [0.00e+00, 1.17e+02, 8.00e+01, ..., 4.52e+01, 8.90e-02, 2.40e+01],
       [4.00e+00, 1.17e+02, 6.40e+01, ..., 3.32e+01, 2.30e-01, 2.40e+01],
       [2.00e+00, 1.12e+02, 8.60e+01, ..., 3.84e+01, 2.46e-01, 2.80e+01]])

In [32]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,

In [33]:
x_test

array([[  0.   , 140.   ,  65.   , ...,  42.6  ,   0.431,  24.   ],
       [  6.   , 111.   ,  64.   , ...,  34.2  ,   0.26 ,  24.   ],
       [  5.   , 139.   ,  64.   , ...,  28.6  ,   0.411,  26.   ],
       ...,
       [  0.   , 179.   ,  50.   , ...,  37.8  ,   0.455,  22.   ],
       [  6.   ,  80.   ,  66.   , ...,  26.2  ,   0.313,  41.   ],
       [  3.   , 113.   ,  50.   , ...,  29.5  ,   0.626,  25.   ]])

In [34]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

- Normalization : Given input data into same range
  - it involves rescaling the features or attributes of a dataset to ensure that they all have similar scales or ranges. Normalization is performed to make the algorithm less sensitive to the magnitude of individual features, which can help improve the performance of KNN and other distance-based algorithms. Here's why normalization is important in KNN:

- Standerd Scalar normalization methord
  - z = (x - u) / s
      - where:
          - x : Mean of training data
          - u : Exact values
          - Standard deviation of training data

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train) #
normalized_x_train_data = scaler.transform(x_train) # x train after scaled
normalized_x_test_data = scaler.transform(x_test)

Print normalized_x_traindata

In [36]:
normalized_x_train_data

array([[-0.57352194,  0.79503452, -3.5852932 , ..., -0.54846836,
        -0.71753294, -0.4717971 ],
       [-0.57352194, -1.26346855,  0.14973337, ..., -0.22633664,
         0.17464927, -0.7254904 ],
       [ 0.0136683 ,  0.03497185, -0.0577681 , ...,  0.38075776,
        -0.26998877, -0.38723267],
       ...,
       [-1.16071217, -0.12337454,  0.56473633, ...,  1.64450528,
        -1.15635872, -0.81005483],
       [ 0.0136683 , -0.12337454, -0.26526958, ...,  0.15774349,
        -0.74659425, -0.81005483],
       [-0.57352194, -0.28172093,  0.87598854, ...,  0.80200693,
        -0.70009615, -0.4717971 ]])

Print x_test

In [37]:
normalized_x_test_data

array([[-1.16071217,  0.60501885, -0.21339421, ...,  1.32237356,
        -0.16246192, -0.81005483],
       [ 0.60085854, -0.31339021, -0.26526958, ...,  0.2816403 ,
        -0.65941032, -0.81005483],
       [ 0.30726342,  0.57334957, -0.26526958, ..., -0.41218187,
        -0.22058454, -0.64092597],
       ...,
       [-1.16071217,  1.84012069, -0.99152475, ...,  0.72766884,
        -0.09271478, -0.9791837 ],
       [ 0.60085854, -1.29513782, -0.16151884, ..., -0.70953422,
        -0.50538538,  0.62754054],
       [-0.27992682, -0.25005165, -0.99152475, ..., -0.30067473,
         0.40423362, -0.7254904 ]])

In [38]:
from sklearn.neighbors import KNeighborsClassifier
# for create model
# create object
# assing value for k as 7
knn = KNeighborsClassifier(n_neighbors=7)
# To create model fit training data
knn.fit(normalized_x_train_data, y_train)
# y_predict : to check if the machine trained or not
y_pred = knn.predict(normalized_x_test_data)
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0])

- Compare y_pred and y_test manually

In [39]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

***Performance Evaluation***
-----

  - Performance evaluation methods in machine learning are used to assess the effectiveness and quality of a predictive model. The choice of evaluation method depends on the type of problem (classification, regression, clustering, etc.) and the nature of the data. Here are some common performance evaluation methods:
  - Performance evaluation methods:
    - Accuracy score
    - Recall
    - precision
    - F1 score
------
- All performance evaluation methords are based on ``confusion matrix``


- ***Confusion Matrix***

  - A confusion matrix is a fundamental tool in the evaluation of classification models. It is a table that summarizes the performance of a classification algorithm on a set of data for which the true values (ground truth) are known. The confusion matrix provides insight into the model's ability to correctly classify data points into different classes. It is particularly useful when dealing with binary classification problems, where there are two classes (positive and negative), but it can also be extended to multiclass problems.

  - The confusion matrix consists of four key metrics:

  1. **True Positives (TP):** The number of instances that are actually positive and were correctly classified as positive by the model.

  2. **True Negatives (TN):** The number of instances that are actually negative and were correctly classified as negative by the model.

  3. **False Positives (FP):** The number of instances that are actually negative but were incorrectly classified as positive by the model. Also known as a Type I error.

  4. **False Negatives (FN):** The number of instances that are actually positive but were incorrectly classified as negative by the model. Also known as a Type II error.

  - Here is a representation of a confusion matrix:

  - ```
                 Actual Positive    Actual Negative
Predicted Positive      TP              FP
Predicted Negative      FN              TN
```

  - From the confusion matrix, various performance metrics can be calculated to assess the model's performance, including:

    - **Accuracy:** The ratio of correctly classified instances (TP and TN) to the total number of instances. It provides an overall measure of model correctness but can be misleading when dealing with imbalanced datasets.

    - **Precision (Positive Predictive Value):** The ratio of true positives (TP) to the total number of predicted positives (TP + FP). It quantifies the model's ability to avoid false positives.

    - **Recall (True Positive Rate, Sensitivity):** The ratio of true positives (TP) to the total number of actual positives (TP + FN). It quantifies the model's ability to find all positive instances.

    - **F1-Score:** The harmonic mean of precision and recall. It provides a balance between precision and recall.

    - **Specificity (True Negative Rate):** The ratio of true negatives (TN) to the total number of actual negatives (TN + FP). It quantifies the model's ability to avoid false alarms in negative instances.

    - **False Positive Rate (FPR):** The ratio of false positives (FP) to the total number of actual negatives (FP + TN). It quantifies the rate of false alarms.

    - **False Negative Rate (FNR):** The ratio of false negatives (FN) to the total number of actual positives (FN + TP). It quantifies the rate of missed positive instances.

    - The choice of which performance metric to prioritize depends on the specific problem and the trade-offs between false positives and false negatives. For example, in a medical diagnosis scenario, you might want to minimize false negatives (missed diagnoses) at the cost of some false positives (false alarms).

    - A confusion matrix provides a comprehensive view of a model's performance and is a valuable tool for evaluating the quality of a classification model.

***Accuracy Score***
----
The accuracy score is a common performance metric used in classification problems to measure the overall correctness of a predictive model. It represents the ratio of correctly predicted instances (both true positives and true negatives) to the total number of instances in the dataset. The accuracy score provides a general measure of how well the model is performing across all classes.

The formula for calculating accuracy is:

\[ \text{Accuracy} = \frac{\text{Number of Correct Predictions}}{\text{Total Number of Predictions}} \]

In a confusion matrix, accuracy is calculated as:

\[ \text{Accuracy} = \frac{\text{True Positives (TP) + True Negatives (TN)}}{\text{Total Number of Instances}} \]

Here's a breakdown of the terms in the formula:

- **True Positives (TP):** The number of instances that are actually positive and were correctly classified as positive by the model.

- **True Negatives (TN):** The number of instances that are actually negative and were correctly classified as negative by the model.

- **Total Number of Instances:** The sum of true positives, true negatives, false positives, and false negatives in the dataset.

Accuracy is a straightforward metric to understand and interpret. It is expressed as a percentage, where higher values indicate better model performance. However, it has limitations, especially in situations with imbalanced datasets where one class significantly outnumbers the other. In such cases, a high accuracy score can be misleading because a model that always predicts the majority class may achieve a high accuracy but may not be useful.

Therefore, while accuracy is a valuable metric for assessing model performance, it should be used in conjunction with other metrics like precision, recall, F1-score, and the confusion matrix to provide a more comprehensive evaluation, especially when dealing with imbalanced datasets or when different types of errors have different costs or implications.

- Equation for Accuracy score
    - ``Acuracy score = (TP + TN) / (TN + FP + FN)``

- print confusion matrix

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix_con = confusion_matrix(y_test, y_pred)
matrix_con

array([[135,  25],
       [ 27,  44]])

- calulate accuracy score

In [41]:
score = accuracy_score(y_test, y_pred)
score

0.7748917748917749

- So here accuracy is approximatly 76%.
- The accuracy will change when we run code again, because When you split your dataset into training and testing sets (or use techniques like k-fold cross-validation), there is an element of randomness involved. Different random splits can lead to different training and testing sets, which in turn can result in variations in the model's performance.

Predicting if the patient is diabetec or not

In [44]:
print(knn.predict([[3,110,70,32,0,30.7,0.10,40]]))

[1]
