In [ ]:
import numpy as np
import pandas as pd
credit_score = pd.read_csv('/content/Credit Score Classification Dataset.csv')
credit_score

Age  Gender    Income            Education Marital Status  \
0     25  Female   50000.0    Bachelor's Degree         Single   
1     30    Male  100000.0      Master's Degree        Married   
2     35  Female   75000.0            Doctorate        Married   
3     40    Male  125000.0  High School Diploma         Single   
4     45  Female  100000.0    Bachelor's Degree        Married   
..   ...     ...       ...                  ...            ...   
159   29  Female   27500.0  High School Diploma         Single   
160   34    Male   47500.0   Associate's Degree         Single   
161   39  Female   62500.0    Bachelor's Degree        Married   
162   44    Male   87500.0      Master's Degree         Single   
163   49  Female   77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [ ]:
credit_score.head()

Age  Gender    Income            Education Marital Status  \
0   25  Female   50000.0    Bachelor's Degree         Single   
1   30    Male  100000.0      Master's Degree        Married   
2   35  Female   75000.0            Doctorate        Married   
3   40    Male  125000.0  High School Diploma         Single   
4   45  Female  100000.0    Bachelor's Degree        Married   

   Number of Children Home Ownership Credit Score  
0                   0         Rented         High  
1                   2          Owned         High  
2                   1          Owned         High  
3                   0          Owned         High  
4                   3          Owned         High

In [ ]:
credit_score.tail()

Age  Gender   Income            Education Marital Status  \
159   29  Female  27500.0  High School Diploma         Single   
160   34    Male  47500.0   Associate's Degree         Single   
161   39  Female  62500.0    Bachelor's Degree        Married   
162   44    Male  87500.0      Master's Degree         Single   
163   49  Female  77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High

In [ ]:
credit_score.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='object')

In [ ]:
credit_score.dtypes

Age                     int64
Gender                 object
Income                float64
Education              object
Marital Status         object
Number of Children      int64
Home Ownership         object
Credit Score           object
dtype: object

In [ ]:
credit_score.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [ ]:
median_of_inome = credit_score['Income'].median()
median_of_inome

82500.0

In [ ]:
credit_score['Income'].fillna(median_of_inome, inplace=True)

In [ ]:
credit_score.isna().sum()

Age                   0
Gender                6
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [ ]:
credit_score.dropna(subset=['Gender'],inplace=True)

In [ ]:
credit_score.isna().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

**encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
credit_score['Gender'] = le.fit_transform(credit_score['Gender'])
credit_score['Education'] = le.fit_transform(credit_score['Education'])
credit_score['Marital Status'] = le.fit_transform(credit_score['Marital Status'])
credit_score['Home Ownership'] = le.fit_transform(credit_score['Home Ownership'])
credit_score['Credit Score'] = le.fit_transform(credit_score['Credit Score'])

In [ ]:
credit_score

Age  Gender    Income  Education  Marital Status  Number of Children  \
0     25       0   50000.0          1               1                   0   
1     30       1  100000.0          4               0                   2   
2     35       0   75000.0          2               0                   1   
3     40       1  125000.0          3               1                   0   
4     45       0  100000.0          1               0                   3   
..   ...     ...       ...        ...             ...                 ...   
159   29       0   27500.0          3               1                   0   
160   34       1   47500.0          0               1                   0   
161   39       0   62500.0          1               0                   2   
162   44       1   87500.0          4               1                   0   
163   49       0   77500.0          2               0                   1   

     Home Ownership  Credit Score  
0                 1             1  
1                 0             1  
2                 0             1  
3                 0             1  
4                 0             1  
..              ...           ...  
159               1             2  
160               1             0  
161               0             1  
162               0             1  
163               0             1  

[158 rows x 8 columns]

In [ ]:
x = credit_score.iloc[:,:-1].values
y = credit_score.iloc[:,-1].values

In [ ]:
x

array([[2.50e+01, 0.00e+00, 5.00e+04, ..., 1.00e+00, 0.00e+00, 1.00e+00],
       [3.00e+01, 1.00e+00, 1.00e+05, ..., 0.00e+00, 2.00e+00, 0.00e+00],
       [3.50e+01, 0.00e+00, 7.50e+04, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       ...,
       [3.90e+01, 0.00e+00, 6.25e+04, ..., 0.00e+00, 2.00e+00, 0.00e+00],
       [4.40e+01, 1.00e+00, 8.75e+04, ..., 1.00e+00, 0.00e+00, 0.00e+00],
       [4.90e+01, 0.00e+00, 7.75e+04, ..., 0.00e+00, 1.00e+00, 0.00e+00]])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1,
       1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1,
       1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1,
       1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2,
       0, 1, 1, 1])

In [ ]:
y.ndim

1

In [ ]:
x.ndim

2

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1,
       0, 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.9583333333333334